### PR TITLE
Adds a HTML version of the repo

### PR DESCRIPTION
**Pull request by Shakil-Shahadat**
If you accept this PR, then also turn on GitHub pages from the settings, and you will have a website of the repo.

Here is the version from my fork https://shakil-shahadat.github.io/android-foss/

### CODE REVIEW

**Review by offa — APPROVED** [review]
Nice idea. Now, as long as the actual data is kept at a single place and remains easy to use we can give it a try :-).

**Comment by offa** [comment]
https://offa.github.io/android-foss/

**Comment by Shakil-Shahadat** [comment]
Now you should add this link as the website of the repo in the right sidebar to let people know about it. Also, you should hide Releases, Packages, Deployments, etc. from the right sidebar. Cheers.

**Comment by offa** [comment]
Done.

**Pull request merged**
