### PR TITLE
Make it work for older python versions

### PR DESCRIPTION
**Pull request by Ammar64**

### CODE REVIEW

**Comment by offa** [comment]
I have some more fixed on the `ci` branch. Can you merge/rebase it into this PR?

**Comment by Ammar64** [comment]
> Can you merge/rebase it into this PR?

👍

**Comment by Ammar64** [comment]
It now shows the error we want to see  🥳
image

**Review by offa — APPROVED** [review]

**Comment by offa** [comment]
I'm going to fix those :+1:

**Pull request merged**
