### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by alltheseas**
added Zap.Store app store

### CODE REVIEW

**Comment by offa** [comment]
Thanks for your submission. Instead linking to the Github organization, please link to the app project instead.

Which is https://github.com/zapstore/zapstore I guess

**Review by offa — CHANGES_REQUESTED** [review]
- [x] Link to app project

**Review by alltheseas — COMMENTED** [review]
fixed zapstore repo

**Review by offa — APPROVED** [review]
:+1:

**Pull request merged**
