### PR TITLE
Add 'Recurring Expense Tracker'

### PR DESCRIPTION
**Pull request by DennisBauer**

### CODE REVIEW

**Comment by offa** [comment]
Thanks for your contribution and your project! :+1: 

According to [Virustotal](https://www.virustotal.com/gui/file/f7d4c4d73ad86a357bb997346fb48506e854694628230ac56c8c4496f1ec4a8c/detection) linked on Izzys repo it's marked as malicious (Trojan-Spy.AndroidOS.Banker).

**Comment by DennisBauer** [comment]
Thanks for your response.
I'm not really sure why this is shown to you. I just tested both URLs, the one from izzysoft and the apk download link from GitHub and both look fine for me.
https://www.virustotal.com/gui/url/9686d19c63e3f59358220826aba711071760c051c7e18f89427453dc66c82829
https://www.virustotal.com/gui/url/94f41cdd9c4204d89afc4bbad58b1636d8bb3732f54c2c6832ef9ffb1ae86c4e

**Comment by DennisBauer** [comment]
I have the suspicion that this is a false positive. Checking previous versions of the app, all were fine until I triggered a rescan which makes Virustotal detect the same issue also for previous apks.

**Comment by DennisBauer** [comment]
I just rescanned and now out of a sudden Ikarus doesn't detect anything anymore. The hash stayed the same.

**Comment by offa** [comment]
Wired, now none shows any issues … wired :man_shrugging:.

**Pull request merged**
