### PR TITLE
Moves 'Noice' to Music category

### PR DESCRIPTION
**Pull request by Shakil-Shahadat**

### CODE REVIEW

**Comment by offa** [comment]
As far as I understand the description, it creates noise (in the literal sense) not music. Could the Health category fit better here?

**Comment by Shakil-Shahadat** [comment]
I have tested this app. This is basically a background music generator. It generates music like rain, thunderstorms, sea waves, etc. This is more suited to the music category than health. The name Noice is just a misnomer.

**Review by offa — APPROVED** [review]

**Comment by offa** [comment]
Thanks for the clarification, 'noise' is really misleading here.

**Comment by Shakil-Shahadat** [comment]
Done

**Review by offa — APPROVED** [review]

**Pull request merged**
