### PR TITLE
Added 2 more adblockers

### PR DESCRIPTION
**Pull request by opusforlife2**
DNS66 and Personal DNS Filter.

### CODE REVIEW

**Comment by opusforlife2** [comment]
Also, I saw all the F-Droid links contain "/app/" in the URL, but it is redirected to "/packages/", and the F-Droid app also shares URLS which contain "/packages/", not "/app/". I think you should replace all occurrences of the one with the other.

**Comment by sreeharimkl** [comment]
F-Droid app shares URL which contain "/app" for me!

**Comment by opusforlife2** [comment]
@sreeharimkl That's strange. I'm on the recommended 1.9 version. Which version are you on?

**Comment by sreeharimkl** [comment]
@opusforlife2 v1.8 . may be latest update replaces "/app" with "packages"

**Comment by opusforlife2** [comment]
@sreeharimkl Confirmed. All my recent links are 'packages', while the older ones are 'app'.

**Comment by offa** [comment]
First, thanks for your contribution @opusforlife2.

The usage of `app` dates back to localized `package` urls (#46). I've just checked your two links and I get redirected to `package` too. Upstream repositories use both versions (or completely different) on their readme's. No preference from my side.

**Comment by opusforlife2** [comment]
Ah! Well in that case, it makes sense to keep the /app/ URL. I didn't know about the localisation factor.

**Comment by offa** [comment]
The current `/package/` urls don't redirect to the localized urls. However, I couldn't find whether on version is deprecated or what's the default. At least both get you to the same destination :smile: .

**Pull request merged**
