### PR TITLE
update check.sh

### LINKED ISSUE #115: What about automating testing normal links, too?
I've made a short script:
```
#!/bin/bash

LINKS=$(grep "http" "$SOURCE_FILE" \
| grep -oP "http.*" \
| sed "s|)$||" \
| sed "s|) .*||" \
| grep -v img.shields.io \
| grep -v travis-ci.org)

mapfile -t LINKS <<< "$LINKS"

for link in "${LINKS[@]}"
do
    echo "Testing $link"
    STATUS_CODE="$(curl -LI "$link" -o /dev/null -w '%{http_code}\n' -s)"
    if [[ "$STATUS_CODE" != "200" ]]
    then
        FALSE_LINKS+=("$link")
    fi
done

if [ -n "${FALSE_LINKS[*]}" ]
then
    echo "Some links weren't reachable."
    for link in "${FALSE_LINKS[@]}"
    do
        echo "$link"
    done
    exit 1
fi
```

### PR DESCRIPTION
**Pull request by szaimen**
fix #115

### CODE REVIEW

**Comment by offa** [comment]
The F-Droid links seem to slow down the overall build noticeable as they take quite some time to check. Typically the overall build time should stay within 5 min.

**Comment by szaimen** [comment]
> The F-Droid links seem to slow down the overall build noticeable as they take quite some time to check. Typically the overall build time should stay within 5 min.

I wonder why this is the case?
Maybe f-droid is throtteling/limiting the requests?

**Comment by szaimen** [comment]
It was much faster on my own pc...

**Comment by offa** [comment]
Potentially, but the F-Droid website is not the fastest anyway … :smile: . Or the amount of queries is limited by Travis. Since each we query each url on each build it could look like a an (poor) attack from the outside.

As it's still possible to execute the script without effort locally, let's better remove the availability check from the build for now. Probably having two scripts or an argument to keep the basic format checking in the ci build and check the links locally.

**Comment by szaimen** [comment]
I have one idea which I will try out before abandoning the idea to run it every time ;)

**Comment by szaimen** [comment]
This is still needing too long (7min). I'll close this and open a new one.

**Pull request closed without merging**
