### PR TITLE
Add Sleuth

### PR DESCRIPTION
**Pull request by BWPanda**
A logic puzzle game.

### CODE REVIEW

**Comment by shuvashish76** [comment]
Checked the [release apk](https://codeberg.org/BWPanda/sleuth/releases), no tracker found from [AppManager](https://github.com/MuntashirAkon/AppManager) scanner | [pithus](https://beta.pithus.org/report/997643ca85541cc5ba1e9e2a3363eb7e8eee14f9868622b16a401c5c126fe56e) report.
Game [instructions](https://codeberg.org/BWPanda/sleuth/wiki/Instructions).

@BWPanda That's a different kind of board game or perhaps I've no knowledge/experience about board games, game rules idea copied from some other games or it's designed by you?

**Comment by offa** [comment]
Thanks @shuvashish76

**Comment by BWPanda** [comment]
Thanks guys. I'll answer your questions for posterity:
- Android app, no dependencies
- I guess it's a type of board game, but only virtually (I've never seen a real-life game like this)
- It's a clone/remake of Sherlock (see wiki credits for link)
- I briefly considered app stores, but have decided against uploading to them (see https://codeberg.org/BWPanda/sleuth/issues/8 for my reasoning)

**Comment by offa** [comment]
My personal comment:

I don't see an argument against building from source. Forking (a single) repo is necessary for the submitter of the build recipe, which isn't necessarily the actual developer – that's a usual workflow for submissions to most projects though.

However, you have considered it and clearly documented your decision, so questions answered, thanks! :+1:

**Pull request merged**
