### PR TITLE
Update contribution docs

### PR DESCRIPTION
**Pull request by offa**
Related to #302.

/cc @IzzySoft

### CODE REVIEW

**Comment by IzzySoft** [comment]
:heart_eyes: Thanks!

**Comment by shuvashish76** [comment]
> Packages not available on F-Droid, but on IzyOnDroid

IMO we should clearly mention that if package available in both then contributors should add only F-Droid address because that's the main priority of this repo from the beginning. Doesn't matter for whatever reason devs prefer both repo.

**Comment by IzzySoft** [comment]
I second that move by @shuvashish76 – my repo should only serve as "amendment". Maybe with exceptions when apps are no longer updated at F-Droid.org for some reason (like permanent build failures due to e.g. build dependencies not working out) – but I have no strong opinion on that part.

**Comment by shuvashish76** [comment]
> with exceptions when apps are no longer updated at F-Droid.org for some reason (like permanent build failures due to e.g. build dependencies not working out)

+1 _Exceptions_ should be addressed when necessary 👍🏿 but we don't need to add them as a rule/criteria.

**Comment by offa** [comment]
Thanks @shuvashish76 @IzzySoft for your feedback.

> IMO we should clearly mention that if package available in both then contributors should add only F-Droid address because that's the main priority of this repo from the beginning.

Indeed, seems my wording doesn't match my intention :sweat_smile:.


---

How about?

> IzzyOnDroid can be linked using `https://...` only, if the package is *not* available on F-Droid and not marked by NonFreeComp.

**Comment by IzzySoft** [comment]
Sounds good to me!

**Comment by offa** [comment]
Thanks for your review!

**Comment by IzzySoft** [comment]
Thanks for accepting and implementing my request! :heart_eyes:

**Comment by offa** [comment]
Some links are on the way already :-)

**Comment by IzzySoft** [comment]
Yay, cool :star_struck:

**Pull request merged**
