### PR TITLE
Added Tachiyomi

### PR DESCRIPTION
**Pull request by Nan123721**
Not available on F-Droid

### CODE REVIEW

**Comment by offa** [comment]
Thanks for your PR.

The app was listed earlier but got removed. 

It seems to include firebase (https://github.com/tachiyomiorg/tachiyomi/issues/5672) and proprietary components (https://github.com/tachiyomiorg/tachiyomi/issues/3063 and the  [FOSS / fdroid flavour has been removed](https://github.com/tachiyomiorg/tachiyomi/commit/eaf1ef831add3932ffbe4b76f6268151a98dd2b1)).

**Comment by Nan123721** [comment]
Was not aware of this. I won't be using this anymore.

**Comment by Nan123721** [comment]
Well I'm a little confused now, there is an up to date version of Tachiyomi with no anti features on F-Droid.

**Comment by offa** [comment]
Me too …

Searching on the F-Droid website lists it, but the [actual page](https://f-droid.org/app/eu.kanade.tachiyomi) ends in a 404. The current version 0.12.3 is listed on [F-Droid data](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/eu.kanade.tachiyomi.yml) – sed'ing away all proprietary parts.

**Comment by offa** [comment]
@Nan123721 Since it's on F-Droid again, we can add it I guess.

**Review by offa — APPROVED** [review]

**Comment by offa** [comment]
Thanks! :+1:

**Pull request merged**
